import merge from 'lodash/merge'

var _defaultState = Object.freeze(
	 [{
		   "first_name":"John",
			  "last_name":"Doe",
			  "zip":"01234",
			  "npi":12345
			 },{
			   "first_name":"Jane",
			    "last_name":"Doe",
			    "zip":"93110",
			    "npi":23456
			 },{
			   "first_name":"Bran",
			    "last_name":"Doe",
			    "zip":"93110",
			    "npi":54321
			 },{
			   "first_name":"Jack",
			    "last_name":"Dob",
			    "zip":"94101",
			    "npi":35467
			 },{
			   "first_name":"John",
			    "last_name":"Doe",
			    "zip":"54312",
			    "npi":99999
			 },{
			   "first_name":"Jack",
			    "last_name":"Dob",
			    "zip":"11002",
			    "npi":23556
			 },{
			   "organization_name":"Johns Hopkins",
			    "zip":"01234",
			    "npi":22222
			 },{
			   "organization_name":"Mercy Hospital",
			    "zip":"93110",
			    "npi":33333
			 },{
			   "organization_name":"General Hospital",
			    "zip":"11002",
			    "npi":44533
			 },{
 		   "first_name":"John",
 			  "last_name":"Doe",
 			  "zip":"91011",
 			  "npi":34567
 			 },{
 			   "first_name":"Janathan",
 			    "last_name":"Doe",
 			    "zip":"93110",
 			    "npi":23456
 			 },{
 			   "first_name":"Brant",
 			    "last_name":"Doe",
 			    "zip":"93110",
 			    "npi":54321
 			 },{
 			   "first_name":"Jackery",
 			    "last_name":"Dob",
 			    "zip":"94101",
 			    "npi":35467
 			 },{
 			   "first_name":"Brent",
 			    "last_name":"Doe",
 			    "zip":"54312",
 			    "npi":99999
 			 },{
 			   "first_name":"Jack",
 			    "last_name":"Dobbler",
 			    "zip":"11002",
 			    "npi":23556
 			 },{
 			   "organization_name":"Johns Hopkins Hospital",
 			    "zip":"01234",
 			    "npi":22222
 			 },{
 			   "organization_name":"Mercy Hospital Redwood City",
 			    "zip":"93110",
 			    "npi":33333
 			 },{
 			   "organization_name":"General Hospital Near Somewhere",
 			    "zip":"11002",
 			    "npi":44533
 			 },
			 {
			   "first_name":"Jobe",
			   "last_name":"Something",
			   "zip":"11002",
			   "npi":23556
			 },
			 {
			   "first_name":"JohnathanG",
			   "last_name":"Dobbler",
			   "zip":"11002",
			   "npi":23556
			 },
			 {
			   "first_name":"JohanT",
			   "last_name":"Odfjell",
			   "zip":"11002",
			   "npi":23556
			 },
			 {
			   "first_name":"JustIT",
			   "last_name":"AnotherName",
			   "zip":"11002",
			   "npi":23556
			 },
			 {
			   "first_name":"JohncyW",
			   "last_name":"Phillips",
			   "zip":"11002",
			   "npi":23556
			 },
			 {
			   "first_name":"JohnathanT",
			   "last_name":"Dobbler",
			   "zip":"11002",
			   "npi":23556
			 },
			 {
			   "first_name":"Jona",
			   "last_name":"Odfjell",
			   "zip":"11002",
			   "npi":23556
			 },
			 {
			   "first_name":"Junt",
			   "last_name":"AnotherName",
			   "zip":"11002",
			   "npi":23556
			 },
			 {
			   "first_name":"Jobhncy",
			   "last_name":"Phillips",
			   "zip":"11002",
			   "npi":23556
			 },
			 {
			   "first_name":"Johnothan Thompson",
			   "last_name":"Dobbler",
			   "zip":"11002",
			   "npi":23556
			 },
			 {
			   "first_name":"Jihan",
			   "last_name":"Odfjell",
			   "zip":"11002",
			   "npi":23556
			 },
			 {
			   "first_name":"Jast",
			   "last_name":"AnotherName",
			   "zip":"11002",
			   "npi":23556
			 },
			 {
			   "first_name":"Johncy",
			   "last_name":"Phillips",
			   "zip":"11002",
			   "npi":23556
			 },
			 {
			   "first_name":"Johathan Thompson",
			   "last_name":"Dobbler",
			   "zip":"11002",
			   "npi":23556
			 },
			 {
			   "first_name":"Joan",
			   "last_name":"Odfjell",
			   "zip":"11002",
			   "npi":23556
			 },
			 {
			   "first_name":"Jut",
			   "last_name":"AnotherName",
			   "zip":"11002",
			   "npi":23556
			 },
			 {
			   "first_name":"Johncie",
			   "last_name":"Phillips",
			   "zip":"11002",
			   "npi":23556
			 },
			 {
			   "first_name":"JobeTwo",
			   "last_name":"Something",
			   "zip":"11002",
			   "npi":23556
			 },
			 {
			   "first_name":"JohnathanGTwo",
			   "last_name":"Dobbler",
			   "zip":"11002",
			   "npi":23556
			 },
			 {
			   "first_name":"JohanTTwo",
			   "last_name":"Odfjell",
			   "zip":"11002",
			   "npi":23556
			 },
			 {
			   "first_name":"JustITTwo",
			   "last_name":"AnotherName",
			   "zip":"11002",
			   "npi":23556
			 },
			 {
			   "first_name":"JohncyWTwo",
			   "last_name":"Phillips",
			   "zip":"11002",
			   "npi":23556
			 },
			 {
			   "first_name":"JohnathanTTwo",
			   "last_name":"Dobbler",
			   "zip":"11002",
			   "npi":23556
			 },
			 {
			   "first_name":"JonaTwo",
			   "last_name":"Odfjell",
			   "zip":"11002",
			   "npi":23556
			 },
			 {
			   "first_name":"JuntTwo",
			   "last_name":"AnotherName",
			   "zip":"11002",
			   "npi":23556
			 },
			 {
			   "first_name":"JobhncyTwo",
			   "last_name":"Phillips",
			   "zip":"11002",
			   "npi":23556
			 },
			 {
			   "first_name":"JohnothTwo",
			   "last_name":"Dobbler",
			   "zip":"11002",
			   "npi":23556
			 },
			 {
			   "first_name":"JihanTwo",
			   "last_name":"Odfjell",
			   "zip":"11002",
			   "npi":23556
			 },
			 {
			   "first_name":"JastTwo",
			   "last_name":"AnotherName",
			   "zip":"11002",
			   "npi":23556
			 },
			 {
			   "first_name":"JohncyTwo",
			   "last_name":"Phillips",
			   "zip":"11002",
			   "npi":23556
			 },
			 {
			   "first_name":"JohathanTwo",
			   "last_name":"Dobbler",
			   "zip":"11002",
			   "npi":23556
			 },
			 {
			   "first_name":"JoanTwo",
			   "last_name":"Odfjell",
			   "zip":"11002",
			   "npi":23556
			 },
			 {
			   "first_name":"JutTwo",
			   "last_name":"AnotherName",
			   "zip":"11002",
			   "npi":23556
			 },
			 {
			   "first_name":"JohncieTwo",
			   "last_name":"Phillips",
			   "zip":"11002",
			   "npi":23556
			 }]
);

const providersReducer = (state = _defaultState, action) => {
  let nextState;
  Object.freeze(state);

  switch(action.type) {
 
    default:
      return state;
  }
};

export default providersReducer;
